### ISSUE TITLE
Unable to bind() successfully. Error: cannot assign requested address

### ISSUE THREAD

**Issue by HappySamuel** [takiaine/ifm_o3mxxx#1]
Here i attached the details of explanation on what i have did so far and what difficulties i faced.

[ifm_o3m error and difficulties explanation.pdf](https://github.com/takiaine/ifm_o3mxxx/files/2627225/ifm_o3m.error.and.difficulties.explanation.pdf)

I have tried with using connect() to replace the bind() in order to check whether the connection can be successful or not. The answer i got is yes, but no ROS data (point cloud) is received.

Will need help on using ifm_o3m

**Comment by takiaine** [comment]
It might be that you are trying to bind to and address that does not exist. What is your computers IP address, IFM ip address and how does your lanch file look like?

**Comment by HappySamuel** [comment]
My computer IP address: 192.168.1.2

The launch file parameter is as below:
name="Port" value="42000" 
name="IP" value="192.168.1.10" 
name="OutDepthImageTopic" value="ifm_o3mxxx/depth/raw" 
name="PointCloudTopic" value="ifm_o3mxxx_pc" 
name="RawTopic" value="ifm_o3mxxx_raw" 
name="FrameID" value="world"

**Comment by takiaine** [comment]
so the ip address of the launch file name="IP" value="192.168.1.10" needs to be the same as your computers IP address, this is basically needed if you have multiple ethernet connections and you need to choose the one that is connected to the same network as IFM. IFM itself also need to be set so that it send the data over ethernet to specific ip address(or broadcast the data) and port.

**Comment by HappySamuel** [comment]
Just to double confirm with you... Here is my current settings for these parts.

**[current]** sensor's setting:
IP: 192.168.1.10
Port 42000
IP destination: 255.255.255.255
Netmask 255.255.255.0

**[current]** launch file setting:
IP: 192.168.1.10
Port: 42000

**[current]** ethernet setting:
Mode: Manual
IP: 192.168.1.2
Netmask: 255.255.255.0
Gateway: 192.168.1.1

For UDP connection, inside my launch file, i should put the IP address as either 255.255.255.255 or 192.168.1.2.
Due to use the UDP, the IP address must be the local host address. That's UDP. The bind operation connects to the local address, not to the sensor address... so that all incoming data on port 42000 is forwarded to the socket operation

Is that correct?

**Comment by takiaine** [comment]
Yes that is correct.
