### ISSUE TITLE
Misleading Typo in node name

### ISSUE THREAD

**Issue by pfrydlewicz** [takiaine/ifm_o3mxxx#2]
Hi, I wonder, if the first line in the main function is as intended:
ros::init(argc, argv, "imf_o3mxxx_node");

Seems like there is a typo in the node name. Should be ifm_o3mxxx_node.

Indeed a minor thing, but I was struggling a bit with that ;-)

Some variables follow that typo, however there is no functional impact.

Best regards,
Paul

**Comment by takiaine** [comment]
Thanks for pointing that out.

**Comment by pfrydlewicz** [comment]
Thanks for fixing
